In [1]:
import pandas as pd

In [2]:
!kaggle datasets download mexwell/fake-reviews-dataset

Dataset URL: https://www.kaggle.com/datasets/mexwell/fake-reviews-dataset
License(s): Attribution 4.0 International (CC BY 4.0)
Downloading fake-reviews-dataset.zip to /content
100% 4.78M/4.78M [00:01<00:00, 2.74MB/s]

In [3]:
!ls

fake-reviews-dataset.zip  sample_data

In [5]:
import zipfile
with zipfile.ZipFile("fake-reviews-dataset.zip", "r") as zip_ref:
    zip_ref.extractall()

In [8]:
df = pd.read_csv("fake reviews dataset.csv")

In [9]:
df.head()

,category,rating,label,text_
0,Home_and_Kitchen_5,5.0,CG,"Love this! Well made, sturdy, and very comfor..."
1,Home_and_Kitchen_5,5.0,CG,"love it, a great upgrade from the original. I..."
2,Home_and_Kitchen_5,5.0,CG,This pillow saved my back. I love the look and...
3,Home_and_Kitchen_5,1.0,CG,"Missing information on how to use it, but it i..."
4,Home_and_Kitchen_5,5.0,CG,Very nice set. Good quality. We have had the s...

In [10]:
print(df.columns)
df.info()

Index(['category', 'rating', 'label', 'text_'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40432 entries, 0 to 40431
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  40432 non-null  object
 1   rating    40432 non-null  float64
 2   label     40432 non-null  object
 3   text_     40432 non-null  object
dtypes: float64(1), object(3)
memory usage: 1.2+ MB

In [16]:
df = df.rename(columns={
    "text_": "review_text"
})

In [17]:
df["label"] = df["label"].map({"fake": 0, "real": 1})

In [19]:
df = df[["review_text", "label"]]
df.dropna(inplace=True)
df = df.sample(frac=1).reset_index(drop=True)

In [20]:
df["label"].value_counts()

Series([], Name: count, dtype: int64)

In [22]:
df.to_csv("fake reviews dataset.csv", index=False)
print("Dataset ready")

Dataset ready